---
- name: Add users to groups
  ldap_attrs:
    server_uri: "{{ldap_server_uri}}"
    bind_dn: "{{ldap_basedn}}"
    bind_pw: "{{ldap_bind_pw}}"
    dn: "cn={{item.0.name}},ou=groups,{{ldap_basedn}}"
    name: uniqueMember
    values: "uid={{item.1}},ou=people,{{ldap_basedn}}"
    state: present
  with_subelements:
    - "{{ldap_groups}}"
    - members

- name: Remove dummy entry
  ldap_attrs:
    server_uri: "{{ldap_server_uri}}"
    bind_dn: "{{ldap_basedn}}"
    bind_pw: "{{ldap_bind_pw}}"
    dn: "cn={{item.name}},ou=groups,{{ldap_basedn}}"
    name: uniqueMember
    values: "uid=dummy,ou=people,{{ldap_basedn}}"
    state: absent
  with_items: "{{ldap_groups}}"
